"""empty message

Revision ID: ea4f10bf9212
Revises: b3e8b3eb84a5
Create Date: 2026-01-21 11:51:42.940585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4f10bf9212'
down_revision = 'b3e8b3eb84a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('starship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starship.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('favorite_planet')
    op.drop_table('favorite_people')
    op.drop_table('favorite_starship')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_starship',
    sa.Column('starship_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['starship_id'], ['starship.id'], name='favorite_starship_starship_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_starship_user_id_fkey'),
    sa.PrimaryKeyConstraint('starship_id', 'user_id', name='favorite_starship_pkey')
    )
    op.create_table('favorite_people',
    sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], name='favorite_people_people_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_people_user_id_fkey'),
    sa.PrimaryKeyConstraint('people_id', 'user_id', name='favorite_people_pkey')
    )
    op.create_table('favorite_planet',
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='favorite_planet_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_planet_user_id_fkey'),
    sa.PrimaryKeyConstraint('planet_id', 'user_id', name='favorite_planet_pkey')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
